defmodule Di.Channel do
  defstruct [:ad_channel,
             :channel_director,
             :created_at,
             :description_long,
             :description_short,
             :forum_id,
             :id,
             :key,
             :name,
             :network_id,
             :old_id,
             :premium_id,
             :tracklist_server_id,
             :updated_at,
             :asset_id,
             :asset_url,
             :banner_url,
             :description,
             :similar_channels,
             :images]
end
